#!/bin/bash
set -euo pipefail

SERVICE_NAME="${1:?Usage: ./bootstrap.sh <service_name>}"
SKIP_INFRA="${OML_BOOTSTRAP_SKIP_INFRA:-0}"
SKIP_DEV_VARS="${OML_BOOTSTRAP_SKIP_DEV_VARS:-0}"
KV_NAMESPACE_ID="${OML_BOOTSTRAP_KV_NAMESPACE_ID:-0154d85d8ec744069f871b097435751f}"
PROD_BUCKET_NAME="oml-${SERVICE_NAME}-uploads"
DEV_BUCKET_NAME="oml-${SERVICE_NAME}-uploads-dev"
PROD_DB_NAME="oml-${SERVICE_NAME}-db-prod"
DEV_DB_NAME="oml-${SERVICE_NAME}-db-dev"

require_command() {
  local command_name="$1"

  if command -v "$command_name" >/dev/null 2>&1; then
    return
  fi

  echo "Error: required command '$command_name' is not installed." >&2
  exit 2
}

require_turso_auth() {
  if turso auth whoami >/dev/null 2>&1; then
    return
  fi

  echo "Error: Turso CLI is not authenticated. Run 'turso auth login' first." >&2
  exit 2
}

require_wrangler_auth() {
  if npx wrangler whoami >/dev/null 2>&1; then
    return
  fi

  echo "Error: Wrangler is not authenticated. Run 'npx wrangler login' first." >&2
  exit 2
}

r2_bucket_exists() {
  local bucket_name="$1"

  npx wrangler r2 bucket list \
    | awk -F':[[:space:]]*' '/^name:/{print $2}' \
    | grep -Fxq "$bucket_name"
}

ensure_r2_bucket() {
  local bucket_name="$1"

  if r2_bucket_exists "$bucket_name"; then
    echo "R2 bucket already exists: ${bucket_name}"
    return
  fi

  echo "Creating R2 bucket: ${bucket_name}"
  npx wrangler r2 bucket create "$bucket_name"
}

turso_db_exists() {
  local database_name="$1"

  turso db show "$database_name" >/dev/null 2>&1
}

ensure_turso_db() {
  local database_name="$1"

  if turso_db_exists "$database_name"; then
    echo "Turso database already exists: ${database_name}"
    return
  fi

  echo "Creating Turso database: ${database_name}"
  turso db create "$database_name" --group ohmylike-app
}

write_dev_vars() {
  local db_url
  local dev_token

  db_url="$(turso db show "${DEV_DB_NAME}" --url | tr -d '\r\n')"
  dev_token="$(turso db tokens create "${DEV_DB_NAME}" | tail -n 1 | tr -d '\r\n')"

  if [[ -z "${db_url}" ]]; then
    echo "Error: failed to resolve a dev database URL for ${DEV_DB_NAME}." >&2
    exit 1
  fi

  if [[ -z "${dev_token}" ]]; then
    echo "Error: failed to create a dev database token for ${DEV_DB_NAME}." >&2
    exit 1
  fi

  cat > .dev.vars <<EOF
# Generated by ./bootstrap.sh for local wrangler dev.
TURSO_DATABASE_URL=${db_url}
TURSO_AUTH_TOKEN=${dev_token}
EOF

  chmod 600 .dev.vars 2>/dev/null || true
  echo "Wrote .dev.vars for local development."
}

# Validate service name (lowercase alphanumeric + hyphens only)
if [[ ! "${SERVICE_NAME}" =~ ^[a-z][a-z0-9-]*$ ]]; then
  echo "Error: service_name must be lowercase alphanumeric (hyphens allowed, must start with a letter)"
  exit 1
fi

echo "Bootstrapping oml-${SERVICE_NAME}..."

require_command perl

# 1. Replace service and shared infra placeholders
find . -type f \( -name "*.toml" -o -name "*.yml" -o -name "*.yaml" \
  -o -name "*.ts" -o -name "*.tsx" -o -name "*.md" -o -name "*.json" \
  -o -name "*.html" -o -name "*.css" \) \
  ! -path './.git/*' ! -path '*/node_modules/*' -print0 \
  | xargs -0 perl -pi -e "s/__SERVICE_NAME__/${SERVICE_NAME}/g; s/__KV_NAMESPACE_ID__/${KV_NAMESPACE_ID}/g"

# 2. Create per-service Cloudflare/Turso resources unless this is a CI smoke test
if [[ "${SKIP_INFRA}" == "1" ]]; then
  echo "Skipping infrastructure provisioning (OML_BOOTSTRAP_SKIP_INFRA=1)"
else
  require_command npx
  require_command turso
  require_turso_auth
  require_wrangler_auth

  ensure_r2_bucket "${PROD_BUCKET_NAME}"
  ensure_r2_bucket "${DEV_BUCKET_NAME}"

  ensure_turso_db "${PROD_DB_NAME}"
  ensure_turso_db "${DEV_DB_NAME}"

  if [[ "${SKIP_DEV_VARS}" == "1" ]]; then
    echo "Skipping .dev.vars generation (OML_BOOTSTRAP_SKIP_DEV_VARS=1)"
  else
    write_dev_vars
  fi
fi

# 3. Remove bootstrap.sh (one-time use)
rm -- "$0"

echo ""
echo "Done! oml-${SERVICE_NAME} is ready."
echo "Next:"
echo "  1. Verify GitHub + 1Password auth: gh auth status && op whoami"
echo "  2. Sync GitHub Actions secrets and enable production deploy:"
echo "     ./scripts/sync-github-secrets.sh --turso-production-auth-token-ref 'op://ohmylike-prod/${SERVICE_NAME}-prod/turso/auth_token' --enable-production-deploy"
echo "  3. git add -A && git commit -m 'bootstrap: initialize oml-${SERVICE_NAME}' && git push"
